### ISSUE TITLE
Can not install latest version 0.3.1

### ISSUE THREAD

**Issue by titilambert** [jmoore987/sharp_aquos_rc#4]
Hello ! @jmoore987 
I can not download the 0.3.1 version.
Here my shell output
```
# pip install sharp_aquos_rc==0.3.1
Collecting sharp_aquos_rc==0.3.1
  Could not find a version that satisfies the requirement sharp_aquos_rc==0.3.1 (from versions: 0.2)
No matching distribution found for sharp_aquos_rc==0.3.1
```
There is only the 0.2.0 version available. But I see the 0.3.1 on pypi website.
Maybe you  forget something (upload or anything else ?)

Thanks for your help !

**Comment by titilambert** [comment]
It could be also a pypi issue :/

**Comment by jmoore987** [comment]
Can you try `pip uninstall sharp_aquos_rc ; pip --no-cache search sharp_aquos_rc`?

```
Jeffs-MacBook-Pro-2:zr-hive-udf jmoore$ pip --no-cache search sharp_aquos_rc
sharp_aquos_rc (0.3.1)  - Control Sharp Aquos SmartTVs through the IP interface.
Jeffs-MacBook-Pro-2:zr-hive-udf jmoore$
```

and also
`pip --version`

**Comment by jmoore987** [comment]
Sorry, this was my bad.  Ignore my previous comment.  I am a noob at pypi and missed a (what appears to be crucial) step.

From a virgin AWS instance, I am now able to install:
```
[user@ip-xxx-xxx-xxx-xxx ~]$ sudo pip --no-cache install sharp_aquos_rc==0.3.1
You are using pip version 6.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting sharp-aquos-rc==0.3.1
  Downloading sharp_aquos_rc-0.3.1.tar.gz
Installing collected packages: sharp-aquos-rc
  Running setup.py install for sharp-aquos-rc
Successfully installed sharp-aquos-rc-0.3.1
[user@ip-xxx-xxx-xxx-xxx ~]$
```

Feel free to re-open if you still can't install, but this should do it.
